function [ points ] = load_poff( filename )
%LOAD_POFF Load point set from Plane OFF file
%  Loads a point set from a Plane OFF file
%  (as generated by Bálint Miklós' Mesecina).

poff = importdata(filename, ' ', 1);
points = poff.data;

end