function [ points ] = load_poff( filename )
%LOAD_POFF Load point set from Plane OFF file
%  Loads a point set from a Plane OFF file
%  (as generated by Bálint Miklós' Mesecina).

%% Data Import
poff = importdata(filename, ' ', 1);
points = poff.data;

%% Sanity Tests
% I haven't found any documentation of the POFF format, so let's test
% the assumtions I based on observation:

assert(size(points, 2) == 2, ... Did we actually read 2D data?
       ['Expected 2 columns (each row is a 2D point) in %s. ' ...
        'Detected %d columns instead.'], ...
       filename, size(points, 2))

assert(all(size(poff.textdata) == [1 1])) % We expect a single header line

% Header lines I've seen so far were of the following pattern.
% I don't know the semantics of the two zeros, so if we encounter a file
% that has something else instead, the above import code is probably not
% general enough to interpret it correctly, so it's better to error out.
assert(strcmp(poff.textdata,{['POFF ' int2str(size(points, 1)) ' 0 0']}))

end
