res = 400

load ../test/cartman.npoff
x = cartman(:,1:2);

[mu SIGMA] = EM(x, ...
                'a', 0.0003, ...
                'initial_sigma', 5, ...
                'centers_to_points_ratio', 0.2, ...
                'max_steps', 20, ...
                'input_plot', @(x, SIGMA) scatter(x(:,1),x(:,2)), ...
                'pre_plot', @(mu, SIGMA) plot_gauss_mix( mu, SIGMA, 'res', res ), ...
                'post_plot', @(mu, SIGMA) plot_gauss_mix( mu, SIGMA, 'res', res ));