n = size(coeff_L1ls, 1);

fileID = fopen('output_data.txt','w');

fprintf(fileID, [num2str(n), '\r\n']);

for i=1:n
    [V, D] = eig(squeeze(SIGMA(:,i,:,:)));
    fprintf(fileID, [ ...
        num2str(mu(i,:)), ...
        ' ', ...
        num2str(V(:)'), ...
        ' ', ...
        num2str(diag(D)'),...
        ' ', ...
        num2str(mu_normals(i,:)), ...
        ' ', ...
	num2str(coeff_L1ls(i,:)), ...
	'\r\n'
    ]);
end

fclose(fileID);
