n_reduced = size(coeff_L1ls_reduced, 1);

fileID = fopen('output_data.txt','w');

fprintf(fileID, [num2str(n_reduced), '\r\n']);

for i=1:n_reduced
    [V, D] = eig(squeeze(SIGMA_reduced(:,i,:,:)));
    fprintf(fileID, [ ...
        num2str(mu_reduced(i,:)), ...
        ' ; ', ...
        num2str(V(:)'), ...
        num2str(diag(D)'),...
        ' ; ', ...
        num2str(mu_normals_reduced(i,:)), ...
        '\r\n'
    ]);
end

fclose(fileID);