function [] = txt_output(filename, coeffs, SIGMA, mu, mu_normals)

n = size(coeffs, 1);

fileID = fopen(filename,'w');

fprintf(fileID, [num2str(n), '\r\n']);

for i=1:n
    [V, D] = eig(squeeze(SIGMA(:,i,:,:)));
    fprintf(fileID, [ ...
        num2str(mu(i,:)), ...
        ' ', ...
        num2str(V(:)'), ...
        ' ', ...
        num2str(diag(D)'),...
        ' ', ...
        num2str(mu_normals(i,:)), ...
        ' ', ...
	num2str(coeffs(i,:)), ...
	'\r\n'
    ]);
end

fclose(fileID);

end
